import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { TopBar } from "@/components/TopBar";
import { SelectedCityProvider } from "@/contexts/SelectedCityContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased text-slate-900`}
      >
        <SelectedCityProvider>
          <div className="flex min-h-screen flex-col bg-gray-100">
            <TopBar />
            <div className="flex-1">{children}</div>
          </div>
        </SelectedCityProvider>
      </body>
    </html>
  );
}
