services:
  app-web:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: app-web
    restart: unless-stopped
    env_file:
      - ./.env.app
    ports:
      - "127.0.0.1:3001:3000"
